# Site settings
title: Matagor
email: tere@matagor.com
description: > # this means to ignore newlines until "baseurl:"
  Matagor 체hendab p천hjamaise m체toloogia soojade p채ikesekultuuridega.
description_en: >
  Colourful nordic art with flavours of sunshine
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matagor.com" # the base hostname & protocol for your site


copyright: 2015 Matagor &amp; Haldjas

# Build settings
markdown: kramdown
